Ejercicio 1

In [45]:
import numpy as np
import random

np.random.seed(0)

# Crear dos matrices de iguales dimensiones aleatorias
dimension_aleatoria = random.randint(1, 5)
matriz1 = np.random.randint(0, 10, (dimension_aleatoria, dimension_aleatoria))
matriz2 = np.random.randint(0, 10, (dimension_aleatoria, dimension_aleatoria))

print(dimension_aleatoria)
print(matriz1)
print(matriz2)
print(f"\nLa suma de las matrices es: \n{matriz1 + matriz2}")


3
[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[4 7 6]
 [8 8 1]
 [6 7 7]]

La suma de las matrices es: 
[[ 9  7  9]
 [11 15 10]
 [ 9 12  9]]


Ejercicio 2

In [ ]:
matriz_identidad_4 = np.identity(4)
print(matriz_identidad_4)

Ejercicio 3

In [48]:
dimension_aleatoria = random.randint(1, 5)
matriz3 = np.random.randint(0, 2, (dimension_aleatoria, dimension_aleatoria))
matriz_booleana = matriz3 == 1 
print(matriz3)
print(matriz_booleana)

[[1 1]
 [1 0]]
[[ True  True]
 [ True False]]


Ejercicio 4

In [43]:
secuencia_2 = np.arange(0, 101, 2)
print(secuencia_2)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
